<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el6:
    roles:
      - default
      - master
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever

  el7:
    roles:
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  oel6:
    roles:
      - client
    platform:   el-6-x86_64
    box:        onyxpoint/oel-6-x86_64
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  oel7:
    roles:
      - client
    platform:   el-7-x86_64
    box:        onyxpoint/oel-7-x86_64
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>

